[package]
name = "fm"
version = "0.1.0"
edition = "2024"

[target.'cfg(unix)'.dependencies]
libc = "0.2.178"

[dependencies]
fe = {path = "../fe"}
hints = {path = "../hints"}

[dev-dependencies]
tempfile = "3.20.0"
ff = {path = "../ff"}
